### ISSUE TITLE
Reorganizing our screens

### ISSUE THREAD

**Issue by florentianayuwono** [florentianayuwono/NCL-Academy#18]
So I notice that we are keep adding more and more pages in the screens directory. And there is also repeated component such as the header and footer that always appeared on all pages. Do you guys think it is better to reorganize our directory? For example:

Inside the lib, apart from main.dart, we can also have these directories:
1. templates -> to store the templates screens.
2. components -> to store our custom components such as buttons, header, footer, or styling of the text (?) Because these are the components that always appear in every pages.
3. screens -> to store the actual pages that will be displayed, but we can also group them based on chapters. So inside this directory there will also be log4shell directory, spring4shell, etc. And since we already have templates, essentially we also need to change the past pages to use the templates instead.

Also, is there a way to like save all the import statement in one file? So that we can just add one line of importing that import file to all of our future pages. In the future if we need to add import statement, we can just add it in the import file and all the other pages will automatically have that import statement as well.

However, if we want to work on these, there will be many changes happen in the main.dart and other pages, as we have to like reset the routing of every page as well. So if we want to truly work on this issue, maybe we have to wait until all our current work is finished and hold the progress for awhile.

What do you guys think?

**Comment by ishitamandal06** [comment]
Works. I agree on this too.
So we can create a dart file for constant fonts, buttons, and small widgets
within the screen and then a seperate dart file for the template of the
pages itself.

Then we can just show them how to go about it further.

**Comment by thngyuxuan** [comment]
great! i can work on creating the dart file for the widgets and styling since I did most of them. yall can choose to settle the import statements or reorganizing the file structure.

thanks guys!
