### ISSUE TITLE
Standardize 'back' button in web app

### ISSUE THREAD

**Issue by thngyuxuan** [florentianayuwono/NCL-Academy#24]
Currently the back buttons have different styles on the help, chapter select, and content pages, should decide on one style so it looks neater

Personally I feel the one on the help page is closest to the one in the figma wireframe, you guys let me know what yall think

**Comment by florentianayuwono** [comment]
Is the back button on content pages referring with button with "Chapter Select" written on it? Because actually, the design for that button in Figma is a completely new design altogether. So maybe we also need to develop button design for that one

**Comment by florentianayuwono** [comment]
Other than that, yes I agree that the one on help page is closest. So we can change the back button on chapter select to match the one in help page
