### ISSUE TITLE
Implementation of top navigation bar in the app

### ISSUE THREAD

**Issue by thngyuxuan** [florentianayuwono/NCL-Academy#7]
Is there a better implementation of the top navigation bar in our web app? Currently we have my implementation of the AppBar widget but not sure if there is a better option out there e.g. navigation bar. Ishita, you mentioned about this a few weeks back so I thought it would be great to raise this issue now so we can discuss about it and make the necessary changes before the app becomes bigger. Thanks!

**Comment by florentianayuwono** [comment]
I am not sure about this. Do you mean the header?

**Comment by ishitamandal06** [comment]
no flutter has the widget for a bottom or top navigation bar
we can implement it as a seperate class. Can ask Nicole to design it for us.
